name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up cache for Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Install Buf CLI
        run: |
          curl -sSL https://github.com/bufbuild/buf/releases/download/v1.47.2/buf-Linux-x86_64 -o /usr/local/bin/buf
          chmod +x /usr/local/bin/buf

      - name: Install make and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make

      - name: Run make gen-java
        run: |
          make gen-java

      - name: Run make gen-go
        run: |
          make gen-go

      - name: Check generated files
        run: |
          ls -R generated
          git status
  commit-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Commit and push changes
        run: |
          git config --global user.name "ngdangkietse"
          git config --global user.email "kietnguyen17052001@gmail.com"
          if [ -n "$(git status -s)" ]; then
            git status
            git add .
            git commit -m "chore: regenerate files"
            git push origin main
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
